services:
  db-server:
    container_name: postgres_container
    image: postgres:16.5
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      test_network:
        ipv4_address: 172.27.0.2

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      test_network:
        ipv4_address: 172.27.0.3

  api-server:
    container_name: api_container
    image: base-image:latest
    volumes:
      - type: bind
        source: ./api_ws/src
        target: /home/chunwei/src
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/home/chunwei/src
    networks:
      test_network:
        ipv4_address: 172.27.0.4

  test-client:
    container_name: client_container
    image: base-image:latest
    volumes:
      - type: bind
        source: ./client_ws/src
        target: /home/chunwei/src
    stdin_open: true
    tty: true
    networks:
      test_network:
        ipv4_address: 172.27.0.5

networks:
  test_network:
    name: postgres-test
    driver: bridge
    ipam:
      config:
        - subnet: "172.27.0.0/16"
          gateway: "172.27.0.1"
