import time
import uuid

from fastapi import (
    FastAPI,
    Request
)

def register(app: FastAPI):

    @app.middleware("http")
    async def add_process_time_header(request: Request, call_next):

        """
            A middleware is a function that 
            works with every request before it is processed by any specific path operation. 
            And also with every response before returning it.

            The middleware function recieves:
            - The request
            - A function call_next that will receive the request as a parameter.
                - This function will pass the request to the corresponding path operation
                - Then it returns the response generated by the corresponding path operation
            - You can then futher modify the response before returning it.
        """

        started_at = time.time()
        req_id = str(uuid.uuid4())

        response = await call_next(request)
        return response